Game/urls.py
from django.urls import path
from .views import travel, greet, fight
app_name='Game'
urlpatterns=[
    path('', greet, name='greetings'),
    path('travel/', travel, name='travel'),
    path('fight/', fight, name='fight'),
]

Winterhold/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('Game.urls'))
]

Game/models.py
from django.db import models

# Create your models here.
class Place(models.Model):
    x=models.IntegerField(blank=False, default=0)
    y=models.IntegerField(blank=False, default=0)
    name=models.CharField(max_length=20)
    msg=models.TextField()
    enemy=models.IntegerField(blank=False, default=0,null=True)

    def __str__(self) -> str:
        return self.name

class Enemy(models.Model):
    x=models.IntegerField(blank=False, default=0)
    y=models.IntegerField(blank=False, default=0)
    name=models.CharField(max_length=21)
    damage=models.IntegerField(blank=False, default=0)
    hp=models.IntegerField(blank=False, default=0,null=True)

    def __str__(self) -> str:
        return self.name

class Weapon(models.Model):
    name=models.CharField(max_length=21)
    damage=models.IntegerField(blank=False, default=0)
    cost=models.IntegerField(blank=False, default=0)
    classification=models.CharField(max_length=21)
    block_chance=models.FloatField(blank=False, default=0,null=True)
    dodge_chance=models.FloatField(blank=False, default=0,null=True)
    second_chancee=models.IntegerField(blank=False, default=0,null=True)
    ad_dod_chancee=models.IntegerField(blank=False, default=0,null=True)
    ad_damagee=models.IntegerField(blank=False, default=0,null=True)
    first_hite=models.IntegerField(blank=False, default=0,null=True)
    near_fight_dmge=models.FloatField(blank=False, default=0,null=True)
    crit_chance=models.IntegerField(blank=False, default=20,null=True)


    def __str__(self) -> str:
        return self.name

class Boss(models.Model):
    x=models.IntegerField(blank=False, default=0)
    y=models.IntegerField(blank=False, default=0)
    name=models.CharField(max_length=21)
    damage=models.IntegerField(blank=False, default=0)
    hp=models.IntegerField(blank=False, default=0,null=True)
    drop=models.CharField(max_length=21)

    def __str__(self) -> str:
        return self.name

Game/views.py
from django.shortcuts import render

from Game.models import Place
from Game.models import Enemy
from Game.models import Weapon
from Game.models import Boss
# Create your views here.

x,y = 0,0
enemy='пока что тут никого нету'

def greet(request):
    return render(request, 'Game/greetings.html')

def travel(request):
    global y
    global x
    global enemy
    last=[x, y]
    if request.method == 'POST':
        if request.POST['direction'] == 'w' and Place.objects.filter(x=x,y=y+1):
            y+=1
        elif request.POST['direction']=='s'and Place.objects.filter(x=x,y=y-1):
            y-=1
        elif request.POST['direction']=='a'and Place.objects.filter(x=x-1,y=y):
            x-=1
        elif request.POST['direction']=='d' and Place.objects.filter(x=x+1,y=y):
            x+=1

    current_place=Place.objects.get(x=x, y=y)
    if last!=[x,y] or current_place.name=='Замок':
        msg=current_place.msg
    else:
        msg='Вы не можете пройти дальше'
    
    if current_place.enemy == 1:
        enemy = Enemy.objects.get(x=x, y=y)  
    elif current_place.enemy == 2:
        enemy = Boss.objects.get(x=x, y=y) 
    else:
        enemy='пока что тут никого нету'

    context={'x':x, 'y':y, 'msg':msg, 'place':current_place,'enemy':enemy}
    return render(request, 'Game/travel.html', context)

def fight(request):
    global y
    global x


    current_place=Place.objects.get(x=x, y=y)
    
    if current_place.enemy==2:
         current_enemy=Boss.objects.get(x=x, y=y)
    else:
        current_enemy=Enemy.objects.get(x=x, y=y)

    enemy = current_enemy.name
    hp=current_enemy.hp
    damage=current_enemy.damage

    context={'hp':hp, 'damage':damage,'enemy':enemy}
    return render(request, 'Game/fight.html',context)

templates/Game/fight.html
{% extends 'Layout/basic.html' %}
{% block title %}Файтинг{%endblock%}
{% block content %}
<div class="home">
    <h1 class="text_board">Тут будет файтинг)</h1>
    <h1>
        enemy:{{enemy}}
    </h1>
    <h1>
        hp:{{hp}}
        damage_e:{{damage}}
    </h1>

    <form action="{% url 'Game:travel' %}">
        <button>Вернуться</button>
    </form>

</div>
{% endblock %}

templates/Game/greetings.html
{% extends 'Layout/basic.html' %}
{%block title %}Greetings{%endblock%}
{% block content %}
    <div class="home">
        <h1 class="text_board">
            Ваша история начинается в одном из великих замков материка, Винтерхолде.<br>
            
            В этот день вас вызвала к себе принцесса Анна и поручила особо важную миссию.
            Вам необходимо будет встретится лицом к лицу с одним из богов этого мира.
            Принцесса рассказала вам, что ее родители собираются вступить в сговор со тьмой.
            Ваша миссия заключается в предотвращении данной сделки.
            Единственное, что известно, это то, что бог скрывается в руинах, закрытыми 4 печатями.
            Принцесса желает вам удачи в пути.
        </h1>
    <form action="{% url 'Game:travel' %}">
        <button>Начать игру</button>
    </form>
    </div>
{%endblock%}

templates/Game/travel.html
{% extends 'Layout/basic.html' %}
{% block title %}Главная{%endblock%}
{% block content %}
    <div class="travel">
        <h1>Текущая локация: {{ place.name }}</h1>
        <h2>x:{{ x }}, y:{{y}}</h2>
        <h3>enemy:{{enemy}}</h3>
        <p>{{ msg }}</p>
        <form id='direction_form' action="" method="post">
            {% csrf_token %}
            <input type='hidden' value="" name='direction' id='direction'>
        </form>
        <button id='w'
            onclick="document.getElementById('direction_form').elements.direction.value = 'w'; document.getElementById('direction_form').submit();">Вперед</button>
        <button id='s'
            onclick="document.getElementById('direction_form').elements.direction.value = 's'; document.getElementById('direction_form').submit();">Назад</button>
        <button id='d'
            onclick="document.getElementById('direction_form').elements.direction.value = 'd'; document.getElementById('direction_form').submit();">Направо</button>
        <button id='a'
            onclick="document.getElementById('direction_form').elements.direction.value = 'a'; document.getElementById('direction_form').submit();">Налево</button>
            
            <form action="{% url 'Game:fight' %}">
                <button>Перейти к бою</button>
            </form>
        </div>
{% endblock %}

templates/Layout/basic.html
{% load static %}

<!DOCTYPE html> <!-- вот тут тоже я постарался -->
<html lang="ru">
<head>

    <link rel="shortcut icon" href="{% static 'Game/picture/logo.jpg' %}" type="image/jpg">
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'Game/css/main_css.css' %}">

    <title>{% block title %}{%endblock%}</title>

</head>
<body bgcolor="#000" background="{% static 'Game/picture/background.jpg' %}"></body>

    {%block content %}
    {% endblock %}
    
</body>
</html>